### ISSUE TITLE
Subscribe button w/ Klaviyo integration

### ISSUE THREAD

**Issue by Gallred** [tksventures/cubed-landingpage#3]
We need a way to get users added to an email list - GDA will be taking this over and using it as one point of our IEO sales funnel.

We are now using Klaviyo - https://www.klaviyo.com

I have added Jacob as an admin - @bravetarget , it should be in your Tokes email.

You will need to create a snippet via "Signup Forms"

I'd like each page to redirect to a separate segment, one per website (multichain, tokes, eden, cubed, etc.)

Similar issue:
https://github.com/tksventures/mv-landingpage/issues/3#issue-500483648
https://github.com/tksventures/eden-landingpage/issues/3#issue-500485242
https://github.com/tksventures/tokes-landingpage/issues/1#issue-500485859

**Comment by bunthius** [comment]
@tksventures/engineers this form is ready for engineering. See image below, I left the two notifications of success and failure as display: block but the default state should be display: none until showing the notification is relevant.

![image](https://user-images.githubusercontent.com/6615043/66166769-3252f300-e606-11e9-8b76-dcc48c4022b6.png)
